import Navbar from "@/components/main/Navbar";
import "./globals.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="${inter.className} bg-[#030014] overflow-y-scroll overflow-x-hidden">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
