import Navbar from "@/components/global/Navbar";
import "./globals.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "CHUNGSIANG - ROEURN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="${inter.className} bg-[#1a1824] overflow-y-scroll overflow-x-hidden">
        {/* <StarsCanvas /> */}
        <Navbar />
        {children}
      </body>
    </html>
  );
}
